sudo: required
services:
- docker
script:
- docker -v
- docker build -t quay.io/wantedly/nginx-image-server .
- ruby test/run_test.rb
- script/run -d
- script/run-infrataster
- script/run-perf-checker
notifications:
  slack:
    secure: C5l4fgeuirkGPI4BYZP1onHY1FbYbth5UuGRZzmJ/6OBMdwV4HdHl7Gbt92NiD+7EhtWOh1qtqgFPakoVZjrrva3vS/cR1drvh80qQbF/OjZRsR68p0kjJDEn5uJf66iP0DBkFRWYliE0CILXha6T/5xxOQthuoI7OWfrI8SQi0=
